index:
   path: /
   controller: App\Controller\PinsController::index
   methods: GET

show:
   path: /show/{id<[0-9]+>}
   controller: App\Controller\PinsController::show
   methods: GET

create:
   path: /create
   controller: App\Controller\PinsController::form
   methods: GET|POST
